name: 뉴스 모니터링
on:
    workflow_dispatch:  # 수동 실행 가능
    schedule:
        - cron: "*/5 * * * *"  
jobs:
    news-monitoring:
        runs-on: ubuntu-latest
        steps:
          - name: 저장소에 있는 파일 불러오기
            uses: actions/checkout@v4
    
          - name: Java 17 세팅
            uses: actions/setup-java@v4
            with:
              distribution: temurin
              java-version: '17'
    
          - name: 컴파일 및 코드 실행
            run: |
              javac App.java
              java App
            env:
              KEYWORD: ${{ vars.KEYWORD }}
              NEWS_TITLE: ${{ vars.NEWS_TITLE }}
              NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
              NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              
          - name: 실행 결과로 나온 파일을 커밋
            uses: EndBug/add-and-commit@v9
            with:
                author_name: ${{ github.actor }}
                author_email: ${{ github.actor }}@users.noreply.github.com
                message: "뉴스 자동 업데이트: ${{ vars.KEYWORD }}"
                add: "."